### PR TITLE
Added localized cache for UUIDs. And inserted a proper cache for name / UUID lookups.

### PR DESCRIPTION
**Pull request by psygate**
Not every query has to be passed to the mojang api. This crashed our server repeatedly with timeouts. I've inserted a local lookup cache that is queried first, to avoid high latency http connections.

### CODE REVIEW

**Comment by haveric** [comment]
While I appreciate the effort put into this, I don't believe it is the right approach. I've found something else that I believe solves it just as well, but I would appreciate your help in testing it or finding a sweet spot between our two approaches that works even better.

My approach is to call this within onEnable (as well as deleting the removePlayerFromCache)
```java
public static void addOfflinePlayers() {
    OfflinePlayer[] players = RecipeManager.getPlugin().getServer().getOfflinePlayers();
    for (OfflinePlayer player : players) {
        if (player.getName() != null && player.getUniqueId() != null) {
            addPlayerToCache(player.getName(), player.getUniqueId());
        }
    }
}
```

Advantages:
 - We don't need to store all of the UUIDs manually in files ourselves.
 - Potentially can remove the online check altogether?

Disadvantages:
 - More memory use, especially for older/larger servers. (Not sure if enough to be a concern)
 - Not using a Cache, meaning we're storing UUIDs that may never be getting used.

**Comment by psygate** [comment]
The only approach that will ever fix this properly is to remove all fields that store names and make them store UUIDs. Which would be the fix I'd prefer if I had the time to understand what's going on.

Your approach will lead to two issues. First you need to cache all players at all times in memory. I don't see how that will lead to huge issues, since a name is at most 32 bytes and a UUID is 16 bytes. So even storing a good 50000 players actively will be aroud 2MB of actual data. But startup time will suffer. And the map you use can't be cleared once a player logs out. Both approaches will work in the end, mine is just defering the work cycle in small parts to the join event, yours is simply taking longer to load. I think same validity after all.

The thing I'd prefer is to remove all names alltogether and replace them either by UUIDs, or UUID/name pairs. Names are not unique anymore since Mojang allows name changes, and shouldn't be stored in the first place. Only player UUIDs should be used for identification now. Side effect would be that you can remove the HTTP queries all together, since you can actively load player data with Bukkit.getOfflinePlayer(UUID).

**Comment by haveric** [comment]
You make a good point. I'm not even sure this work is needed as I've already moved most things over to UUIDs. The only place I'm seeing UUIDFetcher being used are the outdated api events and for conversion of data for furnaces and brewing stands (which I need to test to make sure is working as I intended). It's probably also a better approach to convert those one time on load vs whenever they are being accessed. Let me see if I can clean it up a bit more and potentially remove the need to even store UUIDs.

**Comment by psygate** [comment]
Since this is code that actively crashes servers, anything that uses the UUIDFetcher should really be removed. In our case, showing the player name as "INVALID" would be a better solution than completely hanging the server thread and crashing because the WatchDog kicks in. From what I gather, we're not the only ones having that problem, and I think the best solution is to completely remove those parts and set them to use UUIDs instead of names. The querying in the main thread is just a really really really bad pattern and should never have happened in the first place. You can technically switch it out for Futures and do background queries, but from what I gather the code needs the UUID asap, so the future won't help much.

If you want I can move this to a ticket and open up an issue instead of a pull request.

**Comment by haveric** [comment]
Most of that work was already done here: https://github.com/haveric/RecipeManager2/commit/128d40d48a106d9d749a917cdd84491c535f2e64 but I still have a lot of testing to do before I am ready to create a release.

Is there any chance you are able to build the latest and let me know how it is performing compared to the current release? 

If you want to move this to a ticket, that is fine with me.

**Pull request closed without merging**
